In [3]:
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
Q3.Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [5]:
df=pd.read_csv('C:/Users/aabdu/Desktop/Hypothesis testing/BuyerRatio.csv')
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
#(We perform chi square test as both the input and output are discrete in nature)

In [ ]:
Hypothesis : Ho : Proportion of male and females are same
             Ha : Proportion of male and females are not same

In [6]:
df.columns

Index(['Observed Values', 'East', 'West', 'North', 'South'], dtype='object')

In [10]:
df2=df.drop(['Observed Values'], axis=1)
df

In [30]:
observed_values = df2.values

In [31]:
print('Observed Values:-  \n', observed_values)

Observed Values:-  
 [[  50  142  131   70]
 [ 435 1523 1356  750]]


In [32]:
val = stats.chi2_contingency(df2)

In [33]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [34]:
expected_values = val[3]

In [35]:
expected_values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [36]:
no_of_rows= len(df2.iloc[0:2,:0])
no_of_columns= len(df2.iloc[0,0:4])
dof= (no_of_rows - 1) * (no_of_columns - 1)   #finding degree of freedom
print('degree of freedom:- ', dof)
alpha= 0.05

degree of freedom:-  3


In [37]:
from scipy.stats import chi2

In [38]:
chi_square = sum([(o-e)**2./e for o,e in zip(observed_values, expected_values)])

In [39]:
chi_square_statistic = chi_square[0]+ chi_square[1]

In [40]:
print('chi-square_statistic:- ', chi_square_statistic)

chi-square_statistic:-  1.5152956451130446


In [41]:
critical_value = chi2.ppf(q=1-alpha, df=dof)  #p_value is alpha so q_value is 1-alpha.In this case q is 0.95.

In [42]:
print('critical_value:- ', critical_value)

critical_value:-  7.814727903251179


In [ ]:
#to calculate the p value below 

In [43]:
p_value = 1-chi2.cdf(x=chi_square_statistic,df=dof)
print('p_value:- ',p_value)
print("significance_level:- ",alpha)
print("Degrees of Freedom:- ",dof)

p_value:-  0.6787446296467897
significance_level:-  0.05
Degrees of Freedom:-  3


In [44]:
if chi_square_statistic >= critical_value :
    print('Proportions of Male and Female are not same.')
else:
    print('Proportion of Male and Female are same.')
    
if p_value <= alpha:
    print('Proportion of Male and Female are not same.')
else:
    print('proportion of Male and Female are same.')

Proportion of Male and Female are same.
proportion of Male and Female are same.


In [ ]:
#alpha is 0.05. p value is gtreater tnak 0.05 hence accept Ho. That is the male and female proportion across the region are same 

In [ ]:
TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [45]:
df3 = pd.read_csv('C:/Users/aabdu/Desktop/Hypothesis testing/Costomer+OrderForm.csv')

In [46]:
df3.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [47]:
Phillippines = df3.Phillippines.value_counts()

In [48]:
Phillippines

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [49]:
Indonesia = df3.Indonesia.value_counts()

In [50]:
Indonesia

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [51]:
Malta = df3.Malta.value_counts()

In [52]:
Malta

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [54]:
India = df3.India.value_counts()

In [55]:
India

Error Free    280
Defective      20
Name: India, dtype: int64

In [56]:
ErrorFree = [271,267,269,280]
Defective = [29,33,31,20]

In [57]:
chistats_defective = stats.chi2_contingency([ErrorFree,Defective])
print('Test t=%f p-value=%f' % (chistats_defective[0], chistats_defective[1]))
print('Interpret by p-Value')
if chistats_defective[1] < 0.05:
  print('Reject null hypothesis')
else:
  print('Fail to reject null hypothesis')

Test t=3.858961 p-value=0.277102
Interpret by p-Value
Fail to reject null hypothesis
